routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {

  Route::get('/client/login', ['uses'=>'SiteController@login']);

Route::get('/redirect/client/dashboard', 'HomeController@redirectToClientDashboard');
Route::group(['middleware'=>['restrict.access']], function(){

  Route::get('/{bid}', ['as'=>'client.home', 'uses'=>'HomeController@dashboard']);
  Route::get('/', 'SiteController@clientHomeRedirector');
  Route::get('/set-default-business/{id}', 'SiteController@setCurrentBusiness');
    Route::get('/{bid}/reviews', ['as'=>'client.reviews.index', 'uses'=>'ReviewsController@index']);
    Route::get('/{bid}/reviews/{id}', ['as'=>'client.reviews.show', 'uses'=>'ReviewsController@show']);
    //  Route::get('/{bid}/photos', ['as'=>'client.businesses.show.photos', 
    //                          'uses'=>'ProfileController@getPhotos']);
    //  Route::post('/{bid}/photos', 'ProfileController@postPhotos');
    Route::get('/{bid}/leads', 'LeadsController@index');
    Route::get('/{bid}/resumes', 'ResumesController@index');
    //  Route::get('/{bid}/rate-cards', [ 'as'=>'client.businesses.show.rate_cards', 
    //                              'uses'=>'ProfileController@getRateCards']);
    //  Route::post('/{bid}/rate-cards', 'ProfileController@postRateCards');
    //  Route::get('/{bid}/validate/voucher/form', [ 'as'=>'client.voucher.validate.form', 
    //                              'uses'=>'OffersController@validateVoucherForm']);
    //  Route::post('/{bid}/validate/voucher', [ 'as'=>'client.voucher.validate', 
    //                              'uses'=>'OffersController@postValidateVoucher']);
    //  Route::post('/{bid}/voucher/{id}/redeem', [ 'as'=>'client.voucher.redeem', 
    //                              'uses'=>'OffersController@redeemVoucher']);
    //
    //  Route::any('/{bid}/google', 'HomeController@google');
    //  Route::any('/{bid}/api/ratings', 'ReviewsController@getRatingsData');
    Route::any('/{bid}/api/views', 'HomeController@getViewsDataApi');
    Route::any('/{bid}/api/calls', 'HomeController@getCallsDataApi');
    Route::any('/{bid}/api/call_logs', 'HomeController@getCallLogsDataApi');
    //  Route::get('/{bid}/change-request', 'ProfileController@getChangeRequest');
    //  Route::post('/{bid}/change-request', [ 'as'=>'client.post.change-request', 
    //                              'uses'=>'ProfileController@postChangeRequest']);
    //  Route::group(array('prefix'=>'{bid}'), function(){
    //    Route::resource('offers', 'OffersController');
    //    Route::resource('offers', 'OffersController', array('names' => mzk_route_helper('offers', 
    //      'partner')));
    //  });
    //
    //
    //  Route::get('users/logout', 'client\\HomeController@logout');
    //  Route::get('unauthenticated', 'client\\HomeController@unauthenticated');
    //
      Route::group(array('prefix'=>'{bid}'), function(){
        Route::get('call_logs/dispute/{id}', ['uses'=>'Call_logsController@createDispute', 'as'=>'partner.call_logs.disputes.store']);
        Route::post('call_logs/dispute', ['uses'=>'Call_logsController@storeDispute', 'as'=>'partner.call_logs.disputes.create']);
    
        Route::get('call_logs/resolve/{id}', ['uses'=>'Call_logsController@createResolve', 'as'=>'partner.call_logs.resolves.store']);
        Route::post('call_logs/resolve', ['uses'=>'Call_logsController@storeResolve', 'as'=>'partner.call_logs.resolves.create']);
        Route::get('call_logs/reset/{id}', ['uses'=>'Call_logsController@resetCallLog', 'as'=>'partner.call_logs.reset']);
        Route::get('call_logs/billable/{id}', ['uses'=>'Call_logsController@clearToBilled', 'as'=>'partner.call_logs.clear.to.billed']);
    
        Route::group(array('before' => 'client.admin.auth'), function(){
          Route::get('call_logs/export', ['uses'=>'Call_logsController@export', 'as'=>'partner.call_logs.export']);
        });
    
        Route::resource('call_logs', 'Call_logsController');
        Route::resource('call_logs', 'Call_logsController', 
            array('names' => mzk_route_helper('call_logs', 
                  'partner')));
      });
    
    Route::get('users/logout', ['as'=>'users.logout', 'uses'=>'SiteController@logout']);
    //  Route::get('/{bid}/photo/{photoId}', ['as'=>'client.businesses.show.photo','uses'=>'client\\ProfileController@getPhoto']);
    //  Route::post('/{bid}/photo/{photoId}', ['as'=>'client.businesses.edit.photo', 'uses'=>'client\\ProfileController@postPhoto'] );
    //  Route::get('/{bid}/photo/{photoId}/rotate/{degrees}', ['as'=>'client.businesses.rotate.photo',
    //                                                'uses'=>'client\\ProfileController@rotatePhoto']);
  });

});

app/Models/Call_log.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Eloquent, Auth;


use App\Models\Share;
use App\Models\Ad_set;
use App\Models\Photo;

class Call_log extends Eloquent{
  protected $guarded = array();

  public function __construct(){
    parent::__construct();
    $this->table = 'api_calllog';
  }

  public static $rules = [];

  public $fields = array('description', 'dated', 'timed', 'called_number', 'caller_number', 'caller_duration', 'agent_list', 'call_connected_to', 'call_transfer_status', 'call_transfer_duration', 'call_recording_url', 'call_start_time', 'call_pickup_time', 'caller_circle', 'business_id', 'is_downloaded', 'is_lead', 'state', 'is_ppl', 'media_file_name', 'media_file_size', 'media_content_type', 'media_updated_at', 'invoice_item_id', 'type_of_call');

  public $fillables = array('description', 'dated', 'timed', 'called_number', 'caller_number', 'caller_duration', 'agent_list', 'call_connected_to', 'call_transfer_status', 'call_transfer_duration', 'call_recording_url', 'call_start_time', 'call_pickup_time', 'caller_circle', 'business_id', 'is_downloaded', 'is_lead', 'state', 'is_ppl', 'media_file_name', 'media_file_size', 'media_content_type', 'media_updated_at', 'invoice_item_id', 'type_of_call');

  const STATE_CLEAR = 'clear';
  const STATE_UNBILLED = 'unbilled';
  const STATE_DISPUTED = 'disputed';
  const STATE_BILLED = 'billed';
  const STATE_RESOLVED = 'resolved';

  public function scopeOnlyDownloaded($query){
    return $query->where('is_downloaded', '=', 1);
  }

  public function scopeAccessibleByClient($query){
    return $query->whereIn('type_of_call', [0,3]);
  }

  public function isAccessibleByClient(){
    if(in_array($this->type_of_call, [0,3])){
      return true;
    }

    return false;
  }

  public function scopeOnlyNotDownloaded($query){
    return $query->where('is_downloaded', '<>', 1);
  }


  public function scopeWithUrl($query){
    return $query->whereNotIn('call_recording_url', ['None', ' ', '']);
  }

  public function scopeHoursAgo($query, $hours = 3){
    $now = \Carbon\Carbon::now();

    $now->subHours($hours);                  //

    return $query->where('created_at', '<', (date('Y-m-d H:i', strtotime($now))));
  }



  public function scopeByBusiness($query, $business_id){
    return $query->where('business_id', '=', $business_id);
  }

  public function scopeByBusinesses($query, $business_ids){
    return $query->whereIn('business_id', $business_ids);
  }

  public function scopeBillable($query){
    return $query->whereIn('state', [self::STATE_UNBILLED, self::STATE_RESOLVED]);
  }

  public function scopeOnlyConnected($query){
    return $query->where('call_transfer_status', '=', 'Connected');
  }
  public function isConnected(){
    return $this->call_transfer_status == 'Connected' ? true:false;
  }

  public function scopeBetweenDates($query, $start, $end){
    return $query->where('dated', '>', $start)->where('dated', '<=', $end);
  }

  public function beforeCreate(){
    $this->setInitialStatus();
  }

  public function dispute(){
    $this->state = self::STATE_DISPUTED;
    $this->save();
  }

  public function resolve(){
    $this->state = self::STATE_RESOLVED;
    $this->is_lead = 1;
    $this->save();
  }

  public function resetLead(){
    $this->state = self::STATE_CLEAR;
    $this->is_lead = 0;
    $this->save();
  }

  public function makeClearToBillable(){
    $this->state = self::STATE_UNBILLED;
    $this->is_lead = 1;
    $this->save();
  }

  public function comments(){
    //return $this->morphMany('Comment', 'commentable');
  }

  public function getDurationAttribute(){
    if(!strstr($this->caller_duration, ':')){
      return $this->caller_duration>0?$this->caller_duration:0;
    }else{
      sscanf($this->caller_duration, "%d:%d:%d", $hours, $minutes, $seconds);

      $time_seconds = isset($seconds) ? ($hours * 3600) + ($minutes * 60) + $seconds : ($hours * 60) + $minutes;
      return $time_seconds;
    }
  }


  public function isDisputable(){
    
    if($this->isLead()){
      if($this->state!=self::STATE_DISPUTED){
        return true;
      }
    }

    return false;
  }

  public function isClear(){

    if($this->state==self::STATE_CLEAR){
      return true;
    }

    return false;
  }

  public function isResolvable(){

    if($this->isLead()){

      if($this->state==self::STATE_DISPUTED){
        return true;
      }
    }

    return false;
  }
  public function isResetable(){
  
    if(in_array($this->state, [self::STATE_UNBILLED, self::STATE_DISPUTED, self::STATE_RESOLVED])){
      return true;
    }else{
      return false;
    }
  }

  public function canBeResolvedByUser($user = false){
    $user = $user ? $user : Auth::user();
    if($user->hasTheRoles(['admin','moderator','sales-admin','sales'])){
      return true;
    }else{
      return false;
    }
  }

  public function isPotentialLead(){
    return true;
    if($this->duration >= 30){
      return true;
    }else{
      return false;
    }
  }

  public function isLead(){
    if($this->is_lead == 1){
      return true;
    }else{
      return false;
    }
  }
  
  function isPPL(){
    return $this->is_ppl == 1 ? true:false;
  }

  public function setInitialStatus(){
    if($this->isPotentialLead()){
      $this->is_lead = 1;
      $this->state = self::STATE_UNBILLED;
    }else{
      $this->is_lead = 0;
      $this->state = self::STATE_CLEAR;
    }
  }



}

app/Http/Controllers/Call_logsController.php
<?php
namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Validator;
use Auth, DB, URL, View, Redirect, Response;


class Call_logsController extends Controller {

	/**
	 * Call_log Repository
	 *
	 * @var Call_log
	 */
	protected $call_log, $business;

	public function __construct(\App\Models\Call_log $call_log, \App\Models\Business $business)
	{
		$this->call_log = $call_log;
		$this->business = $business;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index($bid)
	{
		$current_business_id = $bid;//mzk_client_get_default_business();
		$business = $this->business->find($current_business_id);

		$user = \App\Models\User::find(\Auth::user()->id);

		if(!$user->hasTheRoles(['admin', 'sales', 'sales-admin'])){
			$merchant_ids = \DB::table('api_merchantuser')->where('user_id', '=', $user->id)->pluck('merchant_id','merchant_id')->all();
			$business_ids = \App\Models\Business::whereIn('merchant_id',  $merchant_ids)->pluck('id','id')->all();
			if(!isset($business_ids[$bid])){
	    	return redirect('/');
			}
		}

		$input = Input::all();
		$start_date = isset($input['start']) ? $input['start'] : \Carbon\Carbon::now()->subDays(30)->toDateString();
		$end_date  = isset($input['end']) ? $input['end'] :  \Carbon\Carbon::now()->toDateString();
		$params = ['start'=>$start_date, 'end'=>$end_date];

		$call_logs = $this->call_log->query()->accessibleByClient();
		$call_logs = $call_logs->byBusiness($business->id)->betweenDates($start_date, $end_date)->orderBy('api_calllog.dated', 'DESC')->orderby('api_calllog.timed', 'DEC');
		$call_logs = $call_logs->paginate(20);

		return View::make('call_logs.index', compact('call_logs', 'params', 'start_date', 'end_date', 'business'));
	}


	public function createDispute($bid, $id)
	{
    return view('call_logs.disputes.create', compact('id'));
	}

	public function storeDispute(){
		$input = Input::all();
		$call_log = \App\Models\Call_log::find($input['call_log_id']);
		$call_log->dispute();

		$data = ['body'=>$input['description'], 
						 'commentable_type'=>'Call_log', 
						 'commentable_id'=>$call_log->id,
						 'type'=>Comment::CALL_LOG_DISPUTE];

		Comment::create($data);

		return redirect()->back()
			->with('notice', 'Dispute has been logged.');
	}


	public function createResolve($bid, $id)
	{
    return view('call_logs.resolves.create', compact('id'));
	}

	public function storeResolve(){
		$input = Input::all();
		$call_log = \App\Models\Call_log::find($input['call_log_id']);
		if($input['action'] == '0'){ // is not a lead
			$call_log->resetLead();

		}else{
			$call_log->resolve();
		}

		$data = ['body'=>$input['description'], 
						 'commentable_type'=>'Call_log', 
						 'commentable_id'=>$call_log->id,
						 'type'=>Comment::CALL_LOG_FOLLOWUP];

		Comment::create($data);

		return redirect()->back()
			->with('notice', 'Dispute has been Resolved.');
	}

	public function resetCallLog($bid, $id){
		$call_log = \App\Models\Call_log::find($id);
		$user = \App\Models\User::find(\Auth::user()->id);

		if($call_log->canBeResolvedByUser($user) && $call_log->isResetable()){
			$call_log->resetLead();
		}

		return redirect()->back();

	}


	public function clearToBilled($bid, $id){
		$call_log = \App\Models\Call_log::find($id);
		$user = \App\Models\User::find(\Auth::user()->id);

		if($call_log->canBeResolvedByUser($user) && $call_log->isClear()){
			$call_log->makeClearToBillable();
		}

		return redirect()->back();
	}

	public function export($bid){
		global $bzness;
		$bzness = $this->business->find($bid);
    $nm = 'call-logs-'.$bzness->slug.'-'.time();
    
		Excel::create($nm, function($excel) {

	    $excel->sheet('Calls', function($sheet) {

				$columns = ['caller_number', 'date'];
				$data = [];
				global $bzness;
				$call_logs = $this->call_log->byBusiness($bzness->id)->orderBy('api_calllog.id', 'DESC')->get()->toArray();
				foreach($call_logs as $call_log){
					$row = array();
					$row['caller_number'] = $call_log['caller_number'];
					$row['date'] = $call_log['dated'].' '.$call_log['timed'];
					$data[] = $row;
				}
	      $sheet->fromArray($data);
		  });

		})->export('csv');

	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('call_logs.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, \App\Models\Call_log::$rules);

		if ($validation->passes()){
			$this->call_log->create($input);
			return redirect()->route('call_logs.index');
		}

		return Redirect::route('call_logs.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$call_log = $this->call_log->findOrFail($id);

		return view('call_logs.show', compact('call_log'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$call_log = $this->call_log->find($id);

		if (is_null($call_log))
		{
			return Redirect::route('partner.call_logs.index');
		}

		return View::make('client.call_logs.edit', compact('call_log'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Call_log::$rules);

		if ($validation->passes())
		{
			$call_log = $this->call_log->find($id);
			$call_log->update($input);

			return Redirect::route('partner.call_logs.show', $id);
		}

		return Redirect::route('partner.call_logs.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->call_log->find($id)->delete();

		return Redirect::route('partner.call_logs.index');
	}

}

resources/views/call_logs/edit.blade.php
@extends('layouts.client')
@section('content')

<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <h1>Edit Call_log</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div>

{{ Form::model($call_log, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('admin.call_logs.update', $call_log->id))) }}

        <div class="form-group">
            {{ Form::label('dated', 'Dated:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('dated', Input::old('dated'), array('class'=>'form-control', 'placeholder'=>'Dated')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('timed', 'Timed:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('timed', Input::old('timed'), array('class'=>'form-control', 'placeholder'=>'Timed')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('called_number', 'Called_number:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('called_number', Input::old('called_number'), array('class'=>'form-control', 'placeholder'=>'Called_number')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('caller_number', 'Caller_number:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('caller_number', Input::old('caller_number'), array('class'=>'form-control', 'placeholder'=>'Caller_number')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('caller_duration', 'Caller_duration:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'caller_duration', Input::old('caller_duration'), array('class'=>'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('agent_list', 'Agent_list:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('agent_list', Input::old('agent_list'), array('class'=>'form-control', 'placeholder'=>'Agent_list')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_connected_to', 'Call_connected_to:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('call_connected_to', Input::old('call_connected_to'), array('class'=>'form-control', 'placeholder'=>'Call_connected_to')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_transfer_status', 'Call_transfer_status:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('call_transfer_status', Input::old('call_transfer_status'), array('class'=>'form-control', 'placeholder'=>'Call_transfer_status')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_transfer_duration', 'Call_transfer_duration:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'call_transfer_duration', Input::old('call_transfer_duration'), array('class'=>'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_recording_url', 'Call_recording_url:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::textarea('call_recording_url', Input::old('call_recording_url'), array('class'=>'form-control', 'placeholder'=>'Call_recording_url')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_start_time', 'Call_start_time:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('call_start_time', Input::old('call_start_time'), array('class'=>'form-control', 'placeholder'=>'Call_start_time')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('call_pickup_time', 'Call_pickup_time:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('call_pickup_time', Input::old('call_pickup_time'), array('class'=>'form-control', 'placeholder'=>'Call_pickup_time')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('caller_circle', 'Caller_circle:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::text('caller_circle', Input::old('caller_circle'), array('class'=>'form-control', 'placeholder'=>'Caller_circle')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('business_id', 'Business_id:', array('class'=>'col-md-2 control-label')) }}
            <div class="col-sm-10">
              {{ Form::input('number', 'business_id', Input::old('business_id'), array('class'=>'form-control')) }}
            </div>
        </div>


<div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      {{ Form::submit('Update', array('class' => 'btn btn-lg btn-primary')) }}
      {{ link_to_route('admin.call_logs.show', 'Cancel', $call_log->id, array('class' => 'btn btn-lg btn-default')) }}
    </div>
</div>

{{ Form::close() }}
@stop

resources/views/call_logs/show.blade.php
@extends('layouts.client')
@section('content')

<h1>Show Call log</h1>



	<table class="table table-striped">
		<thead>
			<tr>
				<th>Date</th>
				<th>Time</th>
				<th>Caller </th>
			</tr>
		</thead>

		<tbody>
				<tr>
					<td>{{{ $call_log->dated }}}</td>
					<td>{{{ $call_log->timed }}}</td>
					<td>{{{ $call_log->caller_number }}}</td>
				</tr>
			</tbody>
		</table>
	<div>
	  @if(strlen($call_log->media_url))
	     <audio controls>
	    <source src="{{ $call_log->media_url }}" type="audio/ogg">
	    <source src="{{ $call_log->media_url }}" type="audio/mpeg">
	  Your browser does not support the audio element.
	    </audio>
	    @endif
	</div>

  @if($call_log->isPotentialLead())
    <i class="fa fa-money" title="This call is a potential lead and is billable."></i>
  @endif
  {{ mzk_call_logs_state_helper($call_log->state) }}
  @if($call_log->isDisputable())
    <a href="javascript:void(0)" class="btn lnk-to-dispute btn-default btn-lg" data-call="{{ $call_log->id }}">DISPUTE</a>
  @endif
  @if($call_log->canBeResolvedByUser())
    @if($call_log->isResolvable())
      <a href="javascript:void(0)" class="btn lnk-to-resolve btn-default btn-lg" data-call="{{ $call_log->id }}">RESOLVE</a>
    @endif
  @endif

@stop